# Generated by Django 4.1 on 2022-09-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='phone_number_integer',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(default='phone number', max_length=50),
        ),
    ]
