# Generated by Django 4.1 on 2022-09-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim_app', '0002_remove_phonenumber_phone_number_integer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='sim_number',
            new_name='sim_network',
        ),
    ]
