# Generated by Django 4.1 on 2022-09-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_app', '0003_rename_sim_number_phonenumber_sim_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
