# Generated by Django 4.1.1 on 2022-10-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim_app', '0006_alter_phonenumber_sim_network'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='sim_network',
            new_name='sim',
        ),
        migrations.RenameField(
            model_name='simnetwork',
            old_name='sim_name',
            new_name='name',
        ),
    ]
